### PR TITLE
reporter: don't commit suicide when shortening fails

### LINKED ISSUE #32: error during shortening kills botthread
```08:52:20 news brockman[4034]: Shortening FeedItem {itemTitle = "WHY IS LITERALLY EVERYTHIGN STILL DUMPING???????????????", itemLink = "http://boards.4chan.org/biz/thread/29452955#29452955"} with "http://go.r"
Feb 23 08:52:20 news brockman[4034]: brockman: HttpExceptionRequest Request {
Feb 23 08:52:20 news brockman[4034]:   host                 = "go.r"
Feb 23 08:52:20 news brockman[4034]:   port                 = 80
Feb 23 08:52:20 news brockman[4034]:   secure               = False
Feb 23 08:52:20 news brockman[4034]:   requestHeaders       = [("Content-Type","application/x-www-form-urlencoded"),("User-Agent","haskell wreq-0.5.3.2")]
Feb 23 08:52:20 news brockman[4034]:   path                 = "/"
Feb 23 08:52:20 news brockman[4034]:   queryString          = ""
Feb 23 08:52:20 news brockman[4034]:   method               = "POST"
Feb 23 08:52:20 news brockman[4034]:   proxy                = Nothing
Feb 23 08:52:20 news brockman[4034]:   rawBody              = False
Feb 23 08:52:20 news brockman[4034]:   redirectCount        = 10
Feb 23 08:52:20 news brockman[4034]:   responseTimeout      = ResponseTimeoutDefault
Feb 23 08:52:20 news brockman[4034]:   requestVersion       = HTTP/1.1
Feb 23 08:52:20 news brockman[4034]: }
Feb 23 08:52:20 news brockman[4034]:  (StatusCodeException (Response {responseStatus = Status {statusCode = 502, statusMessage = "Bad Gateway"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx"),("Date","Tue, 23 Feb 2021 07:52:20 GMT"),("Content-Type","tex>
```

### PR DESCRIPTION
**Pull request by Lassulus**
fixes #32

### CODE REVIEW

File: src/Brockman/Bot/Reporter.hs [hunk 1]
```diff
@@ -146,5 +146,8 @@ feedThread nick configMVar isFirstTime lru chan =
 shortenWith :: FeedItem -> HostName -> IO FeedItem
 item `shortenWith` url = do
   debugM "brockman" ("Shortening " <> show item <> " with " <> show url)
-  r <- post url ["uri" := itemLink item]
-  pure item {itemLink = decodeUtf8 $ BL.toStrict $ r ^. responseBody}
+  E.try (postWith defaults url ["uri" := itemLink item]) >>= \case
+    Left (E.SomeException _) -> do
+      pure item
+    Right response -> do
+      pure item {itemLink = decodeUtf8 $ BL.toStrict $ response ^. responseBody}
```
Comment (kmein) [inline src/Brockman/Bot/Reporter.hs]: `import Data.Functor ((<&>))`

```suggestion
  E.try (postWith defaults url ["uri" := itemLink item]) <&> \case
    Left (E.SomeException _) -> item
    Right response -> item {itemLink = decodeUtf8 $ BL.toStrict $ response ^. responseBody}
```

**Review by kmein — CHANGES_REQUESTED** [review]
see suggestion, also import Data.Functor
